import type { Metadata } from "next";
import { isApparelOnlyLaunch } from "@/lib/launch-mode";
import { resolvePublicSiteUrl } from "@/lib/public-site-url";

const siteUrl = resolvePublicSiteUrl();

/**
 * Stable URL for the dynamic OG image generated by `app/opengraph-image.tsx`.
 * Per-page metadata can override via `buildMetadata({ image })` (e.g. PDPs use product photos).
 */
const DEFAULT_OG_IMAGE_PATH = "/opengraph-image";
const DEFAULT_OG_IMAGE_WIDTH = 1200;
const DEFAULT_OG_IMAGE_HEIGHT = 630;

const FULL_DESCRIPTION =
  "Apparel for makers — made with heat. Plus tools for independent pottery studios to get discovered, take bookings, and sell work.";

const APPAREL_DESCRIPTION =
  "Shop T-shirts, hoodies, and apparel for potters, artists, makers, and creative people. Join our affiliate program and share the culture.";

const FULL_KEYWORDS = [
  "maker apparel",
  "pottery studio merch",
  "independent pottery artists",
  "pottery studios directory",
  "pottery studio software",
  "ceramic studio software",
  "pottery class booking software",
  "sell ceramics online",
  "pottery website builder",
  "pottery studio management",
  "ceramic artist ecommerce",
] as const;

const APPAREL_KEYWORDS = [
  "maker t-shirts",
  "potter apparel",
  "artist hoodies",
  "ceramic artist apparel",
  "creative apparel",
  "affiliate apparel program",
  "PotteryMania shop",
] as const;

export const siteMetadata = {
  name: "PotteryMania",
  get description() {
    return isApparelOnlyLaunch() ? APPAREL_DESCRIPTION : FULL_DESCRIPTION;
  },
  url: siteUrl,
  ogImage: DEFAULT_OG_IMAGE_PATH,
  ogImageWidth: DEFAULT_OG_IMAGE_WIDTH,
  ogImageHeight: DEFAULT_OG_IMAGE_HEIGHT,
  get keywords() {
    return [...(isApparelOnlyLaunch() ? APPAREL_KEYWORDS : FULL_KEYWORDS)];
  },
};

/** Optional Twitter handle (env-driven so we don't hardcode an account that may change). */
function envTwitterHandle(): string | undefined {
  const raw = process.env.NEXT_PUBLIC_TWITTER_HANDLE?.trim();
  if (!raw) return undefined;
  return raw.startsWith("@") ? raw : `@${raw}`;
}

function keywordsForPath(path: string | undefined) {
  const normalized = path || "/";
  if (normalized === "/" || normalized.startsWith("/wear")) return [...APPAREL_KEYWORDS];
  return [...siteMetadata.keywords];
}

export function buildAbsoluteUrl(path = "/") {
  return new URL(path, siteMetadata.url).toString();
}

export function defaultPublicTitle(): string {
  return isApparelOnlyLaunch() ? "PotteryMania — T-Shirts & Apparel for Makers" : "PotteryMania";
}

function envVerification() {
  const google = process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION?.trim();
  const bing = process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION?.trim();
  const yandex = process.env.NEXT_PUBLIC_YANDEX_SITE_VERIFICATION?.trim();
  if (!google && !bing && !yandex) return undefined;
  return {
    ...(google ? { google } : {}),
    ...(bing ? { other: { "msvalidate.01": bing } } : {}),
    ...(yandex ? { yandex } : {}),
  };
}

export function buildMetadata(input: {
  title: string;
  description: string;
  path?: string;
  image?: string;
  imageWidth?: number;
  imageHeight?: number;
  imageAlt?: string;
  keywords?: string[];
  robots?: Metadata["robots"];
  alternates?: Metadata["alternates"];
  /**
   * Defaults to "website". Pass "article" / "profile" for the matching Next.js OG variants;
   * use `"product"` on PDPs and we'll emit it as a raw `og:type` meta via `other` (Next's
   * OpenGraph discriminated union doesn't include `product`, so setting it on `openGraph.type`
   * can blow up the metadata resolver and 5xx the route).
   */
  ogType?: "website" | "article" | "product" | "profile";
  /** Extra meta tags emitted via `<meta name|property=key content=value />` (e.g. product:price:amount). */
  other?: Record<string, string | number | string[]>;
}): Metadata {
  const url = buildAbsoluteUrl(input.path || "/");
  const image = input.image || siteMetadata.ogImage;
  const isDefaultImage = !input.image;
  const imageWidth = input.imageWidth ?? (isDefaultImage ? siteMetadata.ogImageWidth : undefined);
  const imageHeight = input.imageHeight ?? (isDefaultImage ? siteMetadata.ogImageHeight : undefined);
  const imageAlt = input.imageAlt ?? `${input.title} — ${siteMetadata.name}`;
  const twitterHandle = envTwitterHandle();
  /**
   * Only forward types Next.js's OpenGraph discriminated union actually understands.
   * For "product" (or anything else) we pass through via `other.og:type` instead.
   */
  const safeOgType: "website" | "article" | "profile" =
    input.ogType === "article" || input.ogType === "profile" || input.ogType === "website"
      ? input.ogType
      : "website";
  const otherMerged: Record<string, string | number | string[]> = { ...(input.other ?? {}) };
  if (input.ogType && input.ogType !== safeOgType && !("og:type" in otherMerged)) {
    otherMerged["og:type"] = input.ogType;
  }
  return {
    title: input.title,
    description: input.description,
    keywords: [...keywordsForPath(input.path), ...(input.keywords ?? [])],
    robots: input.robots,
    verification: envVerification(),
    alternates: {
      canonical: url,
      languages: {
        "x-default": url,
        en: url,
      },
      ...(input.alternates ?? {}),
    },
    openGraph: {
      title: input.title,
      description: input.description,
      url,
      siteName: siteMetadata.name,
      locale: "en_US",
      images: [
        {
          url: image,
          alt: imageAlt,
          ...(imageWidth ? { width: imageWidth } : {}),
          ...(imageHeight ? { height: imageHeight } : {}),
        },
      ],
      type: safeOgType,
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description: input.description,
      images: [image],
      ...(twitterHandle ? { site: twitterHandle, creator: twitterHandle } : {}),
    },
    other: Object.keys(otherMerged).length > 0 ? otherMerged : undefined,
  };
}
