-- Default wear catalog so /wear/shop is live after migrate deploy (idempotent by slug).
-- Matches prisma/wear-products-seed.cjs; safe to re-run.

INSERT INTO "wear_products" (
  "id",
  "slug",
  "name",
  "subtitle",
  "description",
  "price_cents",
  "currency",
  "images",
  "sort_order",
  "is_active",
  "is_featured",
  "archived_at",
  "external_fulfillment_id",
  "created_at",
  "updated_at"
)
VALUES
  (
    gen_random_uuid(),
    'studio-mark-tee',
    'Studio mark · tee',
    'Heavy cotton, minimal mark.',
    $d1$A quiet signal for people who build with their hands. Cut for everyday wear; print placement kept intentionally spare.$d1$,
    2800,
    'EUR',
    '["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80"]'::jsonb,
    10,
    true,
    true,
    NULL,
    NULL,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'hands-in-the-clay-longsleeve',
    'Hands in the clay · longsleeve',
    'For cool studios and early mornings.',
    $d2$Long sleeves when the kiln is still warming. Same editorial line as the rest of the drop.$d2$,
    3400,
    'EUR',
    '["https://images.unsplash.com/photo-1610701596007-1150281fbcdd?auto=format&fit=crop&w=800&q=80"]'::jsonb,
    20,
    true,
    false,
    NULL,
    NULL,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'quiet-kiln-cap',
    'Quiet kiln · cap',
    'Six-panel, unstructured.',
    $d3$Low-key headwear for kiln days and market runs. One size with adjustable closure.$d3$,
    2400,
    'EUR',
    '["https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=800&q=80"]'::jsonb,
    30,
    true,
    false,
    NULL,
    NULL,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'build-your-space-hoodie',
    'Build your space · hoodie',
    'Warm layer, clean silhouette.',
    $d4$When the studio is cold and the work is long. Fleece-backed; tonal embroidery option later.$d4$,
    5200,
    'EUR',
    '["https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?auto=format&fit=crop&w=800&q=80"]'::jsonb,
    40,
    true,
    false,
    NULL,
    NULL,
    NOW(),
    NOW()
  )
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "subtitle" = EXCLUDED."subtitle",
  "description" = EXCLUDED."description",
  "price_cents" = EXCLUDED."price_cents",
  "currency" = EXCLUDED."currency",
  "images" = EXCLUDED."images",
  "sort_order" = EXCLUDED."sort_order",
  "is_active" = true,
  "is_featured" = EXCLUDED."is_featured",
  "archived_at" = NULL,
  "updated_at" = NOW();
